from datetime import datetime
from enum import Enum
from typing import List, Optional, Dict, Any
from pydantic import BaseModel, Field


class LocationResolutionMethod(str, Enum):
    GPS_COORDINATES = "gps_coordinates"
    DISTRICT_CENTROID = "district_centroid"
    STATE_CENTROID = "state_centroid"
    DEFAULT_FALLBACK = "default_fallback"


class LocationMetadataDTO(BaseModel):
    latitude: float
    longitude: float
    resolved_name: str
    resolution_method: LocationResolutionMethod
    state: Optional[str] = None
    district: Optional[str] = None


class WeatherCurrentDTO(BaseModel):
    time: str
    temperature: float = Field(..., description="Current temperature in Celsius")
    relative_humidity: int = Field(..., description="Current relative humidity in %")
    precipitation: float = Field(..., description="Precipitation in mm for preceding interval")
    weather_code: int = Field(..., description="WMO weather interpretation code")
    weather_description: str = Field(default="Clear sky", description="Human-readable condition")
    wind_speed: float = Field(..., description="Wind speed in km/h at 10m")
    wind_direction: Optional[float] = Field(default=None, description="Wind direction in degrees")


class WeatherForecastDayDTO(BaseModel):
    date: str = Field(..., description="Forecast date (YYYY-MM-DD)")
    weather_code: int = Field(..., description="WMO weather code")
    weather_description: str = Field(default="Clear", description="Human-readable condition")
    temp_max: float = Field(..., description="Maximum temperature in Celsius")
    temp_min: float = Field(..., description="Minimum temperature in Celsius")
    precipitation_sum: float = Field(..., description="Precipitation sum in mm")
    precipitation_probability_max: int = Field(..., description="Max probability of precipitation in %")
    wind_speed_max: float = Field(..., description="Max wind speed in km/h")
    et0_evapotranspiration: Optional[float] = Field(default=None, description="Reference evapotranspiration (ET0) in mm/day")


class WeatherSoilDTO(BaseModel):
    soil_temperature_0_to_10cm: Optional[float] = Field(default=None, description="Soil temperature at 0-10cm depth in Celsius")
    soil_moisture_0_to_1cm: Optional[float] = Field(default=None, description="Volumetric soil moisture at 0-1cm in m3/m3")


class WeatherSignalsDTO(BaseModel):
    """
    Neutral weather signals derived purely from meteorological data.
    These are WEATHER FACTS/SIGNALS, NOT agronomic prescriptions or rules.
    """
    rain_expected: bool = Field(default=False, description="True if precipitation > 0.5mm or rain prob >= 40% in forecast window")
    high_wind_signal: bool = Field(default=False, description="True if wind speed exceeds 20 km/h")
    high_temperature_signal: bool = Field(default=False, description="True if max temperature exceeds 38 C")
    low_temperature_signal: bool = Field(default=False, description="True if min temperature falls below 10 C")
    dry_period_signal: bool = Field(default=False, description="True if 0mm precipitation and rain prob < 20% across forecast window")


class WeatherData(BaseModel):
    """Authoritative weather container capturing provenance and raw weather facts."""
    source: str = "Open-Meteo"
    source_type: str = "weather_model"
    data_origin: str = "production_live"  # or production_cached
    location: LocationMetadataDTO
    current: WeatherCurrentDTO
    forecast_days: List[WeatherForecastDayDTO] = Field(default_factory=list)
    soil: Optional[WeatherSoilDTO] = None
    signals: WeatherSignalsDTO
    timezone: str = "Asia/Kolkata"
    fetched_at: str
    cached: bool = False


class WeatherQueryRequest(BaseModel):
    latitude: Optional[float] = Field(default=None, ge=-90.0, le=90.0)
    longitude: Optional[float] = Field(default=None, ge=-180.0, le=180.0)
    district: Optional[str] = None
    state: Optional[str] = None
    language: str = Field(default="hi-IN")


class WeatherResponse(BaseModel):
    status: str = "ok"
    weather: Optional[WeatherData] = None
    error: Optional[str] = None
    disclaimer: str = (
        "Weather observations and forecasts are generated by the Open-Meteo numerical weather model. "
        "Coordinates correspond to district-area centroids unless specific GPS coordinates were provided. "
        "This data does NOT constitute a field-specific agronomic prescription."
    )
